### ISSUE TITLE
Could not determine kind of name for C.DWORD and C.INPUT

### ISSUE THREAD

**Issue by Apoorva-GA** [AllenDang/w32#65]
Our functional tests running on Gocd are failing for windows saying Could not determine kind of name for C.DWORD and and Could not determine kind of name for C.INPUT. Any help is appreciated.

Please find the stack trace below :

[go] Job Started: 2017-05-02 05:10:48 PDT
[go] Start to prepare Java-FT/888/install/2/windows on DESKTOP-UKKRANG [C:\Program Files (x86)\Go Agent]
[go] Cleaning working directory "C:\Program Files (x86)\Go Agent\pipelines\Java-FT" since stage is configured to clean working directory
[go] Start to update materials.
[go] Start to build Java-FT/888/install/2/windows on DESKTOP-UKKRANG [C:\Program Files (x86)\Go Agent]
[go] Task: cmd /c "rmdir C:\gauge\src /s /q"
[go] Task: cmd /c "rmdir C:\gauge\pkg /s /q"
[go] Task: cmd /c "go get github.com/tools/godep"
[go] Task: cmd /c "go get -d -u -t -v github.com/getgauge/gauge"
[go] Task: cmd /c "cd c:\gauge\src\github.com\getgauge\gauge & c:/gauge/bin/godep restore -v"
[go] Task: cmd /c "cd c:\gauge\src\github.com\getgauge\gauge & go run build/make.go & go run build/make.go --install --prefix %GAUGE_ROOT%"
Build: 
2017/05/02 05:12:10 Execute [go generate ./...]
2017/05/02 05:12:10 Execute [go build -ldflags -X github.com/getgauge/gauge/version.BuildMetadata= -o bin\windows_amd64\gauge.exe]
2017/05/02 05:12:19 Execute [go get -u -d github.com\getgauge\gauge_screenshot]
2017/05/02 05:12:25 Execute [go build -o bin\windows_amd64\gauge_screenshot.exe github.com\getgauge\gauge_screenshot]
# github.com/AllenDang/w32
could not determine kind of name for C.DWORD
could not determine kind of name for C.INPUT
panic: exit status 2
goroutine 1 [running]:
main.runProcess(0x67a51e, 0x2, 0xc042083de8, 0x4, 0x4)
	c:/gauge/src/github.com/getgauge/gauge/build/make.go:75 +0x160
main.compileGaugeScreenshot()
	c:/gauge/src/github.com/getgauge/gauge/build/make.go:114 +0xc6
main.compileGauge()
	c:/gauge/src/github.com/getgauge/gauge/build/make.go:108 +0x124
main.main()
	c:/gauge/src/github.com/getgauge/gauge/build/make.go:239 +0x1a1
exit status 2
Build: 
2017/05/02 05:12:27 Execute [go generate ./...]
2017/05/02 05:12:28 Install bin\windows_amd64\gauge.exe -> deploy\gauge\bin
2017/05/02 05:12:28 Install bin\windows_amd64\gauge_screenshot.exe -> deploy\gauge\bin
panic: GetFileAttributesEx bin\windows_amd64\gauge_screenshot.exe: The system cannot find the file specified.
goroutine 1 [running]:
main.installFiles(0xc04206fc88, 0xc042014e10, 0xc)
	c:/gauge/src/github.com/getgauge/gauge/build/make.go:140 +0x42e
main.copyGaugeBinaries(0xc042014e10, 0xc)
	c:/gauge/src/github.com/getgauge/gauge/build/make.go:167 +0x1c1
main.installGauge()
	c:/gauge/src/github.com/getgauge/gauge/build/make.go:286 +0x57
main.main()
	c:/gauge/src/github.com/getgauge/gauge/build/make.go:232 +0x1bc
exit status 2
[go] Task status: failed
[go] Current job status: failed
[go] Start to create properties Java-FT/888/install/2/windows on DESKTOP-UKKRANG [C:\Program Files (x86)\Go Agent]
[go] Start to upload Java-FT/888/install/2/windows on DESKTOP-UKKRANG [C:\Program Files (x86)\Go Agent]
[go] Job completed Java-FT/888/install/2/windows on DESKTOP-UKKRANG [C:\Program Files (x86)\Go Agent]

**Comment by maddie** [comment]
same here...

**Comment by hut8** [comment]
Why was this PR merged?

https://github.com/AllenDang/w32/pull/56/commits/a61dc27a068a1e324c26b5f5d84655cb4824eecb

**Comment by kesarion** [comment]
@hut8 Thank you for the revert, simply editing and recompiling didn't work, but getting your version did.

**Comment by violarulan** [comment]
Same issue here
`λ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=D:/Rtools/mingw_64/bin/../libexec/gcc/x86_64-w64-mingw32/4.9.3/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-4.9.3/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/home/Jeroen/mingw-gcc-4.9.3/x86_64-493-posix-seh-rt_v3-s/mingw64 --with-gxx-include-dir=/mingw64/x86_64-w64-mingw32/include/c++ --enable-static --disable-shared --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-isl-version-check --disable-cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static --with-mpc=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static --with-isl=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static --with-cloog=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='x86_64-posix-seh, Built by MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64 CFLAGS='-O2 -pipe -I/home/Jeroen/mingw-gcc-4.9.3/x86_64-493-posix-seh-rt_v3-s/mingw64/opt/include -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-zlib-static/include -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/home/Jeroen/mingw-gcc-4.9.3/x86_64-493-posix-seh-rt_v3-s/mingw64/opt/include -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-zlib-static/include -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/home/Jeroen/mingw-gcc-4.9.3/x86_64-493-posix-seh-rt_v3-s/mingw64/opt/lib -L/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-zlib-static/lib -L/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 4.9.3 (x86_64-posix-seh, Built by MinGW-W64 project)`

`λ go version
go version go1.8.1 windows/amd64`

I tried [this](https://github.com/AllenDang/w32/tree/4255f5e69a7e10216b3b58db2129d72a7ac85906) commit and it works for me.

**Comment by PaluMacil** [comment]
@AllenDang We are still having these issues. Also, I too confirm that violarulan recommended a working commit.

**Comment by AllenDang** [comment]
I merged the pull request of hut8, it may fix the issue.

Sorry, I switched my working OS to Mac long time ago, so this repo is not actively maintained well.

**Comment by gonutz** [comment]
I have an actively maintained fork which I use to create both 32 and 64 bit applications, both for work and for private projects. It has diverged quite a bit from this original fork. You could give it a try instead:

https://github.com/gonutz/w32
